-- Migration: Setup Public Sharing for Inspections
-- Generated by Bolt ⚡

-- 1. Add public_token to appointments if it doesn't exist
ALTER TABLE public.appointments
ADD COLUMN IF NOT EXISTS public_token UUID DEFAULT gen_random_uuid();

-- 2. Ensure RLS is enabled on both tables
ALTER TABLE public.appointments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.service_inspections ENABLE ROW LEVEL SECURITY;

-- 3. Policy: Public can view specific appointment fields via public_token
-- This allows the join in the public report page to work.
DROP POLICY IF EXISTS "Public can view appointment via token" ON public.appointments;
CREATE POLICY "Public can view appointment via token" ON public.appointments
    FOR SELECT
    TO anon, authenticated
    USING (public_token IS NOT NULL);

-- 4. Policy: Public can view inspections via appointment token
DROP POLICY IF EXISTS "Public can view inspections via appointment token" ON public.service_inspections;
CREATE POLICY "Public can view inspections via appointment token" ON public.service_inspections
    FOR SELECT
    TO anon, authenticated
    USING (
        EXISTS (
            SELECT 1 FROM public.appointments a
            WHERE a.id = service_inspections.appointment_id
            AND a.public_token IS NOT NULL
        )
    );

-- 5. Backfill existing appointments with a token if they are null
UPDATE public.appointments SET public_token = gen_random_uuid() WHERE public_token IS NULL;
