-- Migration: Allow public access to inspections via appointment token
-- Generated by Bolt ⚡

-- Ensure RLS is enabled
ALTER TABLE public.service_inspections ENABLE ROW LEVEL SECURITY;

-- Drop existing public policy if it exists (to avoid conflicts)
DROP POLICY IF EXISTS "Public can view inspections via appointment token" ON public.service_inspections;

-- Create policy to allow anonymous read if the linked appointment has a public_token
CREATE POLICY "Public can view inspections via appointment token" ON public.service_inspections
    FOR SELECT
    TO anon, authenticated
    USING (
        EXISTS (
            SELECT 1 FROM public.appointments a
            WHERE a.id = service_inspections.appointment_id
            AND a.public_token IS NOT NULL
        )
    );
